import clsx from 'clsx';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(geistSans.variable, geistMono.variable, 'antialiased')}
      >
        <header className="flex flex-row bg-black text-black justify-evenly mb-2">
          <div className="bg-yellow-300 px-4 py-2">Home</div>
          <div className="bg-yellow-300 px-4 py-2">About</div>
        </header>
        {children}
      </body>
    </html>
  );
}
