import { LoadingProvider } from "@/components/context/loading/loadingContext";
import { ThemeProvider } from "@/components/context/theme/themeContext";
import { UserProvider } from "@/components/context/users/userContext";
import { GlobalLoader } from "@/components/features/global-loader";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";

import clsx from "clsx";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  // parallelRoute1,
  // parallelRoute2,
}: Readonly<{
  children: React.ReactNode;
  // parallelRoute1: React.ReactNode;
  // parallelRoute2: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "min-h-screen",
          "flex",
          "flex-col"
        )}
      >
        <LoadingProvider>
          <GlobalLoader />
          <UserProvider>
            <ThemeProvider>
              <Header />
              {/* {parallelRoute1}
              {parallelRoute2} */}
              {children}
              <Footer />
            </ThemeProvider>
          </UserProvider>
        </LoadingProvider>
      </body>
    </html>
  );
}
